
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5332/game_list_dev
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.sql: DEBUG
    flyway: DEBUG
server:
  port: 8080

