CREATE TABLE user_roles
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    roles   VARCHAR(256) NOT NULL
);


CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL,
    email    VARCHAR(256) NOT NULL
);

CREATE TABLE posts
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(256) NOT NULL,
    text VARCHAR(256) NOT NULL,
    user_id BIGINT NOT NULL
);


INSERT INTO user_roles(user_id, roles)
VALUES (1, 'ROLE_USER'),
       (2, 'ROLE_ADMIN'),
       (2, 'ROLE_USER'),
       (3, 'ROLE_ADMIN'),
       (4, 'ROLE_USER'),
       (5, 'ROLE_USER'),
       (6, 'ROLE_USER'),
       (7, 'ROLE_USER'),
       (8, 'ROLE_USER'),
       (9, 'ROLE_USER'),
       (10, 'ROLE_USER'),
       (11, 'ROLE_USER'),
       (12, 'ROLE_USER'),
       (13, 'ROLE_USER'),
       (14, 'ROLE_USER'),
       (15, 'ROLE_USER'),
       (16, 'ROLE_USER'),
       (17, 'ROLE_USER');